"""
Migração inicial: cria BlocoTrabalho e Incremento.
"""

# Generated by Django 6.0.1 on 2026-01-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='NOVO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Incremento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('anexo', models.FileField(blank=True, null=True, upload_to='diario_bordo/anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incrementos', to='diario_bordo.blocotrabalho')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
