"""
Ajusta campos de data para usar default timezone.now.
"""

# Generated by Django 6.0.1 on 2026-01-27 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('diario_bordo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocotrabalho',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incremento',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
