"""
Adiciona vínculo opcional do bloco com contratos.
"""

# Generated by Django 6.0.1 on 2026-01-29 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('contratos', '0004_contrato_status_alter_contrato_data_fim_and_more'),
        ('diario_bordo', '0002_alter_blocotrabalho_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocotrabalho',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocos_trabalho', to='contratos.contrato'),
        ),
    ]
