"""
Adiciona participantes (ManyToMany) em BlocoTrabalho.
"""

# Generated by Django 6.0.1 on 2026-01-29 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('diario_bordo', '0003_blocotrabalho_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blocotrabalho',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='blocos_trabalho', to=settings.AUTH_USER_MODEL),
        ),
    ]
