"""
Adiciona autor do incremento para rastreabilidade.
"""

# Generated by Django 6.0.1 on 2026-01-29 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('diario_bordo', '0004_blocotrabalho_participantes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incremento',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incrementos_criados', to=settings.AUTH_USER_MODEL),
        ),
    ]
