"""
Adiciona campo de imagem em Incremento.
"""

# Generated by Django 6.0.1 on 2026-02-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('diario_bordo', '0006_blocotrabalho_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incremento',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='diario_bordo/imagens/'),
        ),
    ]
