"""
Adiciona campo histórico em BlocoTrabalho (posteriormente removido).
"""

# Generated by Django 5.2.10 on 2026-02-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('diario_bordo', '0008_bloco_leitura'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocotrabalho',
            name='historico',
            field=models.TextField(blank=True, default=''),
        ),
    ]
