"""
Remove campo histórico de BlocoTrabalho.
"""

# Generated by Django 5.2.10 on 2026-02-06 18:35

from django.db import migrations


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    dependencies = [
        ('diario_bordo', '0009_blocotrabalho_historico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocotrabalho',
            name='historico',
        ),
    ]
