# Generated by Django 5.2.10 on 2026-03-08 21:03

import diario_bordo.models
import django.db.models.deletion
from django.db import migrations, models


def migrar_status_antigos(apps, schema_editor):
    BlocoTrabalho = apps.get_model("diario_bordo", "BlocoTrabalho")
    BlocoTrabalho.objects.filter(status="NOVO").update(status="A_FAZER")
    BlocoTrabalho.objects.filter(status="EM_ANDAMENTO").update(status="EM_ANDAMENTO")
    BlocoTrabalho.objects.filter(status="CONCLUIDO").update(status="CONCLUIDO")


class Migration(migrations.Migration):

    dependencies = [
        ('diario_bordo', '0011_incrementociencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiarioMarcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('nome_normalizado', models.CharField(max_length=80, unique=True)),
                ('cor', models.CharField(default=diario_bordo.models.escolher_cor_marcador, max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marcador do Diário',
                'verbose_name_plural': 'Marcadores do Diário',
                'ordering': ['nome'],
            },
        ),
        migrations.RunPython(migrar_status_antigos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blocotrabalho',
            name='status',
            field=models.CharField(choices=[('A_FAZER', 'À Fazer'), ('SOLICITO_TERCEIROS', 'Solicito à terceiros'), ('AGUARDANDO_RESPOSTA', 'Aguardando resposta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='A_FAZER', max_length=24),
        ),
        migrations.CreateModel(
            name='DiarioMarcadorVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcadores_vinculos', to='diario_bordo.blocotrabalho')),
                ('marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos_vinculos', to='diario_bordo.diariomarcador')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('bloco', 'marcador')},
            },
        ),
    ]
