# Generated by Django 5.2.10 on 2026-03-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_bordo', '0012_diariomarcador_alter_blocotrabalho_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocotrabalho',
            name='status',
            field=models.CharField(choices=[('A_FAZER', 'À Fazer'), ('SOLICITO_TERCEIROS', 'Solicitado à terceiros'), ('AGUARDANDO_RESPOSTA', 'Aguardando resposta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído')], default='A_FAZER', max_length=24),
        ),
    ]
