# Generated by Django 5.2.10 on 2026-03-09 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_bordo', '0013_alter_blocotrabalho_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='diario_bordo/anexos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('incremento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='diario_bordo.incremento')),
            ],
            options={
                'ordering': ['criado_em', 'id'],
            },
        ),
    ]
