# Generated by Django 6.0.1 on 2026-01-29 16:46
"""
Migração inicial do app `auditoria`.

Responsabilidade:
- criar a tabela `AuditLog` com estrutura mínima para trilha de auditoria.

Integração arquitetural:
- depende de `contenttypes` para referência genérica do objeto auditado;
- depende do `AUTH_USER_MODEL` para vincular o autor da ação.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Define o estado inicial de banco para auditoria.

    Não contém regra de negócio em runtime; apenas evolução de esquema.
    """

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Criacao'), ('UPDATE', 'Edicao'), ('DELETE', 'Exclusao'), ('M2M_ADD', 'Relacionamento adicionado'), ('M2M_REMOVE', 'Relacionamento removido'), ('M2M_CLEAR', 'Relacionamento limpo')], max_length=20)),
                ('object_id', models.CharField(max_length=64)),
                ('object_repr', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
