# Generated by Django 5.2.10 on 2026-04-01 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento_sistemas', '0002_entrega_status_etapa_data_nula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('NOTA', 'Nota')], default='NOTA', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_sistema_criados', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_sistema', to='acompanhamento_sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Historico do sistema',
                'verbose_name_plural': 'Historicos do sistema',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoHistoricoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='acompanhamento_sistemas/anexos/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='acompanhamento_sistemas.historicosistema')),
            ],
            options={
                'verbose_name': 'Anexo do historico do sistema',
                'verbose_name_plural': 'Anexos do historico do sistema',
                'ordering': ['id'],
            },
        ),
    ]
