# Generated by Django 5.2.10 on 2026-04-10 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento_sistemas', '0003_historicosistema_anexohistoricosistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapasistema',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('ENTREGUE', 'Entregue'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='EtapaProcessoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_etapa', models.CharField(choices=[('AS_IS', 'AS IS'), ('DIAGNOSTICO', 'Diagnóstico'), ('TO_BE', 'TO BE')], max_length=30)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('VALIDACAO', 'Validação'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('RETIRADO_ESCOPO', 'Retirado do escopo')], default='PENDENTE', max_length=20)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_processo_requisito_atualizadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_processo_requisito_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etapa do processo de requisito',
                'verbose_name_plural': 'Etapas do processo de requisito',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoEtapaProcessoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('STATUS', 'Status'), ('NOTA', 'Nota'), ('ANEXO', 'Anexo')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('status_anterior', models.CharField(blank=True, max_length=20)),
                ('status_novo', models.CharField(blank=True, max_length=20)),
                ('justificativa', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_etapa_processo_requisito_criados', to=settings.AUTH_USER_MODEL)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='acompanhamento_sistemas.etapaprocessorequisito')),
            ],
            options={
                'verbose_name': 'Histórico da etapa do processo de requisito',
                'verbose_name_plural': 'Históricos da etapa do processo de requisito',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoHistoricoEtapaProcessoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='acompanhamento_sistemas/anexos/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='acompanhamento_sistemas.historicoetapaprocessorequisito')),
            ],
            options={
                'verbose_name': 'Anexo do histórico da etapa do processo de requisito',
                'verbose_name_plural': 'Anexos do histórico da etapa do processo de requisito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoProcessoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO', 'Criação'), ('EDICAO', 'Edição'), ('EXCLUSAO', 'Exclusão'), ('NOTA', 'Nota'), ('GERACAO_CICLO', 'Geração de ciclo'), ('GERACAO_SISTEMA', 'Geração de sistema')], max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_processo_requisito_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do processo de requisito',
                'verbose_name_plural': 'Históricos do processo de requisito',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoHistoricoProcessoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='acompanhamento_sistemas/anexos/')),
                ('nome_original', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='acompanhamento_sistemas.historicoprocessorequisito')),
            ],
            options={
                'verbose_name': 'Anexo do histórico do processo de requisito',
                'verbose_name_plural': 'Anexos do histórico do processo de requisito',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_requisito_atualizados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_requisito_criados', to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos_requisito', to='acompanhamento_sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Processo de requisito',
                'verbose_name_plural': 'Processos de requisito',
                'ordering': ['ordem', 'id'],
                'unique_together': {('sistema', 'ordem')},
            },
        ),
        migrations.AddField(
            model_name='historicoprocessorequisito',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='acompanhamento_sistemas.processorequisito'),
        ),
        migrations.AddField(
            model_name='etapaprocessorequisito',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='acompanhamento_sistemas.processorequisito'),
        ),
        migrations.AddField(
            model_name='entregasistema',
            name='processo_requisito_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_geradas', to='acompanhamento_sistemas.processorequisito'),
        ),
        migrations.AlterUniqueTogether(
            name='etapaprocessorequisito',
            unique_together={('processo', 'tipo_etapa')},
        ),
    ]
