# Generated by Django 5.2.10 on 2026-03-05 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, unique=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caixa',
                'verbose_name_plural': 'Caixas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo_em_minutos', models.PositiveIntegerField()),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaminhamentos_concluidos', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaminhamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encaminhamentos_destino', to='lousa_digital.caixa')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sei', models.CharField(max_length=120, unique=True, verbose_name='Numero SEI')),
                ('assunto', models.CharField(max_length=255)),
                ('link_sei', models.URLField(blank=True, max_length=500, verbose_name='Link SEI')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluido')], default='EM_ANDAMENTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_lousa_atualizados', to=settings.AUTH_USER_MODEL)),
                ('caixa_origem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_origem', to='lousa_digital.caixa')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCESSO_CRIADO', 'Processo criado'), ('PROCESSO_EDITADO', 'Processo editado'), ('ENCAMINHAMENTO_CRIADO', 'Encaminhamento criado'), ('ENCAMINHAMENTO_DEVOLVIDO', 'Encaminhamento devolvido'), ('NOTA', 'Nota'), ('STATUS_ALTERADO', 'Status alterado')], max_length=30)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encaminhamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='lousa_digital.encaminhamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='lousa_digital.processo')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='lousa_digital.processo'),
        ),
    ]
