# Generated by Django 5.2.10 on 2026-03-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lousa_digital', '0003_prazo_em_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='status',
        ),
    ]
