# Generated by Django 5.2.10 on 2026-03-05 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_criacao_e_grupo(apps, schema_editor):
    Processo = apps.get_model("lousa_digital", "Processo")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    for processo in Processo.objects.filter(criado_por__isnull=True).exclude(atualizado_por__isnull=True):
        processo.criado_por = processo.atualizado_por
        grupo = (
            User.objects.filter(pk=processo.atualizado_por_id)
            .values_list("groups__id", flat=True)
            .order_by("groups__name", "groups__id")
            .first()
        )
        if grupo:
            processo.grupo_insercao_id = grupo
        processo.save(update_fields=["criado_por", "grupo_insercao"])


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lousa_digital', '0004_remove_processo_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_lousa_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processo',
            name='grupo_insercao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_lousa', to='auth.group'),
        ),
        migrations.RunPython(backfill_criacao_e_grupo, migrations.RunPython.noop),
    ]
