# Generated by Django 5.2.10 on 2026-03-05 14:54

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    Processo = apps.get_model("lousa_digital", "Processo")
    Encaminhamento = apps.get_model("lousa_digital", "Encaminhamento")

    ativos_por_processo = set(
        Encaminhamento.objects.filter(data_conclusao__isnull=True).values_list("processo_id", flat=True)
    )
    for processo in Processo.objects.all():
        processo.status = "EM_ABERTO" if processo.id in ativos_por_processo else "CONCLUIDO"
        processo.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ('lousa_digital', '0005_processo_criado_por_processo_grupo_insercao'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('EM_ABERTO', 'Em aberto'), ('CONCLUIDO', 'Concluido')], default='EM_ABERTO', max_length=20),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
