# Generated by Django 5.2.10 on 2026-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lousa_digital', '0006_processo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='encaminhamento',
            name='email_notificacao',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='notificado_72h_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
