# Generated by Django 5.2.10 on 2026-03-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lousa_digital', '0007_encaminhamento_email_notificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventotimeline',
            name='tipo',
            field=models.CharField(choices=[('PROCESSO_CRIADO', 'Processo criado'), ('PROCESSO_EDITADO', 'Processo editado'), ('ENCAMINHAMENTO_CRIADO', 'Encaminhamento criado'), ('ENCAMINHAMENTO_DEVOLVIDO', 'Encaminhamento devolvido'), ('EMAIL_72H_ENVIADO', 'E-mail 72h enviado'), ('NOTA', 'Nota'), ('STATUS_ALTERADO', 'Status alterado')], max_length=30),
        ),
    ]
