# Generated by Django 5.2.10 on 2026-03-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lousa_digital', '0008_alter_eventotimeline_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='arquivo_morto',
            field=models.BooleanField(default=False, verbose_name='Arquivo morto'),
        ),
    ]
