"""
Migração de banco que registra evolução de schema/dados deste app.

Leitura pedagógica: percorra funções e classes observando entradas, validações,
consultas ao banco e efeitos colaterais para entendimento técnico e auditoria.
"""

# Generated by Django 5.2.10 on 2026-02-20 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Classe `Migration` do app `folha_ponto`.

    Responsabilidade pedagógica:
    - Encapsula comportamento de uma entidade/componente do domínio.
    - Deve ser lida em conjunto com os métodos e com os pontos de uso nas views.
    """

    initial = True

    dependencies = [
        ('ramais', '0009_pessoaramal_horario_estudante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(max_length=180)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='FeriasServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('observacao', models.CharField(blank=True, max_length=220)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferias_lancadas', to=settings.AUTH_USER_MODEL)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferias_registros', to='ramais.pessoaramal')),
            ],
            options={
                'verbose_name': 'Ferias',
                'verbose_name_plural': 'Ferias',
                'ordering': ['-data_inicio', '-data_fim'],
            },
        ),
    ]
