"""
Migração de banco que registra evolução de schema/dados deste app.

Leitura pedagógica: percorra funções e classes observando entradas, validações,
consultas ao banco e efeitos colaterais para entendimento técnico e auditoria.
"""

# Generated by Django 5.2.10 on 2026-02-20 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    """Classe `Migration` do app `folha_ponto`.

    Responsabilidade pedagógica:
    - Encapsula comportamento de uma entidade/componente do domínio.
    - Deve ser lida em conjunto com os métodos e com os pontos de uso nas views.
    """

    dependencies = [
        ('folha_ponto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brasao', models.ImageField(blank=True, null=True, upload_to='folha_ponto/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracao RH',
                'verbose_name_plural': 'Configuracoes RH',
            },
        ),
    ]
