# Generated by Django 6.0.1 on 2026-01-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateField()),
                ('categoria', models.CharField(max_length=100)),
                ('imagem_destaque', models.ImageField(blank=True, null=True, upload_to='noticias/')),
            ],
            options={
                'ordering': ['-data_publicacao', '-id'],
            },
        ),
    ]
