# Generated by Django 5.2.10 on 2026-02-20 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtalhoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('imagem', models.ImageField(upload_to='atalhos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('url_destino', models.URLField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Atalho',
                'verbose_name_plural': 'Atalhos',
                'ordering': ['id'],
            },
        ),
    ]
