# Generated by Django 5.2.10 on 2026-02-20 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_atalhoservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atalhoservico',
            name='imagem',
            field=models.ImageField(upload_to='atalhos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])]),
        ),
    ]
