# Generated by Django 5.2.10 on 2026-02-20 17:16

import administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0003_alter_atalhoservico_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atalhoservico',
            name='url_destino',
            field=models.CharField(max_length=500, validators=[administracao.models.validar_url_destino_interna_ou_externa]),
        ),
    ]
