# Generated by Django 5.2.10 on 2026-02-23 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0004_alter_atalhoservico_url_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(choices=[('GERAL', 'Geral'), ('NOTICIAS', 'Noticias'), ('RAMAIS', 'Ramais'), ('DIARIO_BORDO', 'Diario de Bordo'), ('CONTRATOS', 'Contratos'), ('EMPRESAS_PREPOSTOS', 'Empresas e Prepostos'), ('RESERVA_SALAS', 'Reserva de Salas'), ('USUARIOS', 'Usuarios'), ('AUDITORIA', 'Auditoria'), ('ADMINISTRACAO', 'Administracao'), ('FOLHA_PONTO', 'Folha de Ponto')], default='GERAL', max_length=40)),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rf_changelog_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RF/Changelog',
                'verbose_name_plural': 'RFs/Changelog',
                'ordering': ['-criado_em'],
            },
        ),
    ]
