# Generated by Django 5.2.10 on 2026-03-08 16:03

import administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0005_rfchangelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeVisualConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_color', models.CharField(default='#1f2a44', max_length=32, validators=[administracao.models.validar_cor_css_hex_ou_rgb])),
                ('background_color', models.CharField(default='#f2f0ea', max_length=32, validators=[administracao.models.validar_cor_css_hex_ou_rgb])),
                ('brand_text_color', models.CharField(default='#d94f04', max_length=32, validators=[administracao.models.validar_cor_css_hex_ou_rgb])),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identidade visual',
                'verbose_name_plural': 'Identidade visual',
            },
        ),
    ]
