# Generated by Django 5.2.10 on 2026-03-30 12:43

import django.core.validators
from django.db import migrations, models


def seed_atalhos_administracao(apps, schema_editor):
    AtalhoAdministracao = apps.get_model("administracao", "AtalhoAdministracao")
    funcionalidades = [
        "auditoria",
        "configuracoes",
        "noticias",
        "monitoramento",
        "contratos",
        "diario_bordo",
        "licitacoes",
        "reserva_salas",
        "lousa_digital",
        "rfs",
        "rh",
        "usuarios",
    ]
    for funcionalidade in funcionalidades:
        AtalhoAdministracao.objects.get_or_create(
            funcionalidade=funcionalidade,
            defaults={"ativo": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_smtpconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtalhoAdministracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.CharField(choices=[('configuracoes', 'Configuracoes'), ('noticias', 'Noticias'), ('monitoramento', 'Monitoramento'), ('contratos', 'Contratos'), ('diario_bordo', 'Diario de Bordo'), ('licitacoes', 'Licitacoes'), ('reserva_salas', 'Reserva de Salas'), ('lousa_digital', 'Lousa Digital'), ('rfs', 'RFs'), ('rh', 'RH'), ('usuarios', 'Usuarios'), ('auditoria', 'Auditoria')], max_length=40, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='atalhos_administracao/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Card administrativo',
                'verbose_name_plural': 'Cards administrativos',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(seed_atalhos_administracao, migrations.RunPython.noop),
    ]
