# Generated by Django 5.2.10 on 2026-03-30 13:05

from django.db import migrations, models


def seed_missing_atalhos_administracao(apps, schema_editor):
    AtalhoAdministracao = apps.get_model("administracao", "AtalhoAdministracao")
    funcionalidades = [
        "ramais",
        "empresas",
        "prepostos",
        "folha_ponto",
        "sala_situacao",
    ]
    for funcionalidade in funcionalidades:
        AtalhoAdministracao.objects.get_or_create(
            funcionalidade=funcionalidade,
            defaults={"ativo": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0008_atalhoadministracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atalhoadministracao',
            name='funcionalidade',
            field=models.CharField(choices=[('configuracoes', 'Configuracoes'), ('noticias', 'Noticias'), ('ramais', 'Ramais'), ('monitoramento', 'Monitoramento'), ('contratos', 'Contratos'), ('empresas', 'Empresas'), ('prepostos', 'Prepostos'), ('diario_bordo', 'Diario de Bordo'), ('folha_ponto', 'Folha de Ponto'), ('licitacoes', 'Licitacoes'), ('reserva_salas', 'Reserva de Salas'), ('sala_situacao', 'Sala de Situacao'), ('lousa_digital', 'Lousa Digital'), ('rfs', 'RFs'), ('rh', 'RH'), ('usuarios', 'Usuarios'), ('auditoria', 'Auditoria')], max_length=40, unique=True),
        ),
        migrations.RunPython(seed_missing_atalhos_administracao, migrations.RunPython.noop),
    ]
