# Generated by Django 5.2.10 on 2026-03-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0009_alter_atalhoadministracao_funcionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atalhoadministracao',
            name='funcionalidade',
            field=models.CharField(choices=[('administracao', 'Administracao'), ('configuracoes', 'Configuracoes'), ('noticias', 'Noticias'), ('ramais', 'Ramais'), ('monitoramento', 'Monitoramento'), ('contratos', 'Contratos'), ('empresas', 'Empresas'), ('prepostos', 'Prepostos'), ('diario_bordo', 'Diario de Bordo'), ('folha_ponto', 'Folha de Ponto'), ('licitacoes', 'Licitacoes'), ('reserva_salas', 'Reserva de Salas'), ('sala_situacao', 'Sala de Situacao'), ('sala_situacao_old', 'Sala de Situacao (Legado)'), ('lousa_digital', 'Lousa Digital'), ('rfs', 'RFs'), ('rh', 'RH'), ('usuarios', 'Usuarios'), ('auditoria', 'Auditoria')], max_length=40, unique=True),
        ),
    ]
