# Generated by Django 5.2.10 on 2026-03-17 11:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_monitoramento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard de monitoramento',
                'verbose_name_plural': 'Dashboards de monitoramento',
                'ordering': ['titulo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaDashboardMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('sql_texto', models.TextField()),
                ('colunas_json', models.JSONField(blank=True, default=list)),
                ('parametros_json', models.JSONField(blank=True, default=list)),
                ('ultima_validacao_em', models.DateTimeField(blank=True, null=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='monitoramento.dashboardmonitoramento')),
            ],
            options={
                'verbose_name': 'Consulta de dashboard',
                'verbose_name_plural': 'Consultas de dashboard',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GraficoDashboardMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='', max_length=180)),
                ('tipo_grafico', models.CharField(choices=[('linha', 'Linha'), ('barra', 'Barra vertical'), ('barra_horizontal', 'Barra horizontal'), ('dispersao', 'Dispersão X/Y'), ('pizza', 'Pizza'), ('area', 'Área'), ('tabela', 'Tabela')], max_length=32)),
                ('campo_x', models.CharField(blank=True, default='', max_length=180)),
                ('campo_y', models.CharField(blank=True, default='', max_length=180)),
                ('campo_serie', models.CharField(blank=True, default='', max_length=180)),
                ('campo_data', models.CharField(blank=True, default='', max_length=180)),
                ('campo_detalhe', models.CharField(blank=True, default='', max_length=180)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graficos', to='monitoramento.consultadashboardmonitoramento')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graficos', to='monitoramento.dashboardmonitoramento')),
            ],
            options={
                'verbose_name': 'Gráfico de dashboard',
                'verbose_name_plural': 'Gráficos de dashboard',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_monitoramento_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto de monitoramento',
                'verbose_name_plural': 'Projetos de monitoramento',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dashboardmonitoramento',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='monitoramento.projetomonitoramento'),
        ),
        migrations.CreateModel(
            name='ConexaoBancoMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_banco', models.CharField(choices=[('mysql', 'MySQL'), ('sqlserver', 'SQL Server')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('porta', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('database', models.CharField(max_length=255)),
                ('schema', models.CharField(blank=True, default='', max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('senha_criptografada', models.TextField(blank=True, default='')),
                ('status_ultima_conexao', models.CharField(blank=True, default='', max_length=32)),
                ('ultimo_teste_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conexao', to='monitoramento.projetomonitoramento')),
            ],
            options={
                'verbose_name': 'Conexão de banco monitorado',
                'verbose_name_plural': 'Conexões de bancos monitorados',
            },
        ),
        migrations.CreateModel(
            name='SnapshotEsquemaMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrutura_json', models.JSONField(blank=True, default=dict)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots_esquema', to='monitoramento.projetomonitoramento')),
            ],
            options={
                'verbose_name': 'Snapshot de esquema',
                'verbose_name_plural': 'Snapshots de esquema',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
