# Generated by Django 5.2.10 on 2026-03-19 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def bootstrap_setor_nodes(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    SetorNode = apps.get_model("usuarios", "SetorNode")
    for group in Group.objects.all().iterator():
        SetorNode.objects.get_or_create(group=group)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='setor_node', to='auth.group')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='usuarios.setornode')),
            ],
            options={
                'ordering': ['group__name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionResolutionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_code', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('DIRECT_USER', 'Direto do usuário'), ('SETOR', 'Setor'), ('ANCESTRY_PATH', 'Herança de setor')], max_length=20)),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=8)),
                ('ancestry_path', models.CharField(blank=True, default='', max_length=500)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.permission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_resolution_audits', to=settings.AUTH_USER_MODEL)),
                ('source_setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.setornode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_profile_update', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetorGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_grants', to='auth.permission')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='usuarios.setornode')),
            ],
            options={
                'ordering': ['setor__group__name', 'permission__content_type__app_label', 'permission__codename'],
                'unique_together': {('setor', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_grants', to='auth.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'permission__content_type__app_label', 'permission__codename'],
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserSetorMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='usuarios.setornode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username', 'setor__group__name'],
                'unique_together': {('user', 'setor')},
            },
        ),
        migrations.RunPython(bootstrap_setor_nodes, migrations.RunPython.noop),
    ]
