# Generated by Django 6.0.1 on 2026-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Sala",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120, verbose_name="Nome da sala")),
                (
                    "capacidade",
                    models.PositiveIntegerField(verbose_name="Capacidade de pessoas"),
                ),
                ("localizacao", models.CharField(max_length=160, verbose_name="Localizacao")),
                ("televisao", models.BooleanField(default=False, verbose_name="Televisao")),
                ("projetor", models.BooleanField(default=False, verbose_name="Projetor")),
                ("som", models.BooleanField(default=False, verbose_name="Som")),
                (
                    "microfone_evento",
                    models.BooleanField(default=False, verbose_name="Microfone (evento)"),
                ),
                ("som_evento", models.BooleanField(default=False, verbose_name="Som (evento)")),
                (
                    "mesa_som_evento",
                    models.BooleanField(default=False, verbose_name="Mesa de som (evento)"),
                ),
                ("wifi", models.BooleanField(default=False, verbose_name="Wi-Fi")),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
    ]
