# Generated by Django 6.0.1 on 2026-02-04 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reserva_salas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField(verbose_name="Data e hora")),
                ("nome_evento", models.CharField(max_length=160, verbose_name="Nome do evento")),
                (
                    "responsavel_evento",
                    models.CharField(max_length=160, verbose_name="Responsavel pelo evento"),
                ),
                (
                    "quantidade_pessoas",
                    models.PositiveIntegerField(verbose_name="Quantidade de pessoas"),
                ),
                ("televisao", models.BooleanField(default=False, verbose_name="Televisao")),
                ("projetor", models.BooleanField(default=False, verbose_name="Projetor")),
                ("som", models.BooleanField(default=False, verbose_name="Som")),
                (
                    "microfone_evento",
                    models.BooleanField(default=False, verbose_name="Microfone (evento)"),
                ),
                ("som_evento", models.BooleanField(default=False, verbose_name="Som (evento)")),
                (
                    "mesa_som_evento",
                    models.BooleanField(default=False, verbose_name="Mesa de som (evento)"),
                ),
                ("wifi", models.BooleanField(default=False, verbose_name="Wi-Fi")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="reserva_salas.sala",
                    ),
                ),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
    ]
