# Generated by Django 6.0.1 on 2026-02-04 19:02

import random

from django.db import migrations, models


SALA_COLORS = [
    "#1F77B4",
    "#FF7F0E",
    "#2CA02C",
    "#D62728",
    "#9467BD",
    "#8C564B",
    "#E377C2",
    "#17BECF",
    "#BCBD22",
    "#4E79A7",
    "#59A14F",
    "#F28E2B",
    "#E15759",
    "#76B7B2",
]


def assign_colors(apps, schema_editor):
    Sala = apps.get_model("reserva_salas", "Sala")
    for sala in Sala.objects.all():
        if not getattr(sala, "cor", None):
            sala.cor = random.choice(SALA_COLORS)
            sala.save(update_fields=["cor"])


class Migration(migrations.Migration):

    dependencies = [
        ("reserva_salas", "0002_reserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="cor",
            field=models.CharField(
                default="#1F77B4", editable=False, max_length=7, verbose_name="Cor"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(assign_colors, migrations.RunPython.noop),
    ]
