# Generated by Django 6.0.1 on 2026-02-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reserva_salas", "0003_sala_cor"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="duracao_minutos",
            field=models.PositiveIntegerField(default=60, verbose_name="Duracao (minutos)"),
        ),
    ]
