# Generated by Django 6.0.1 on 2026-02-04 20:30

from datetime import time, timedelta

from django.db import migrations, models


def backfill_horas(apps, schema_editor):
    Reserva = apps.get_model("reserva_salas", "Reserva")
    for reserva in Reserva.objects.all():
        if not getattr(reserva, "inicio", None):
            continue
        inicio = reserva.inicio
        duracao = getattr(reserva, "duracao_minutos", None) or 60
        fim = inicio + timedelta(minutes=duracao)
        if fim.date() != inicio.date():
            fim_hora = time(23, 59)
        else:
            fim_hora = fim.time()
        reserva.data = inicio.date()
        reserva.hora_inicio = inicio.time().replace(second=0, microsecond=0)
        reserva.hora_fim = fim_hora.replace(second=0, microsecond=0)
        reserva.save(update_fields=["data", "hora_inicio", "hora_fim"])


class Migration(migrations.Migration):

    dependencies = [
        ("reserva_salas", "0004_reserva_duracao"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="data",
            field=models.DateField(null=True, verbose_name="Data"),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_inicio",
            field=models.TimeField(null=True, verbose_name="Hora de inicio"),
        ),
        migrations.AddField(
            model_name="reserva",
            name="hora_fim",
            field=models.TimeField(null=True, verbose_name="Hora de fim"),
        ),
        migrations.RunPython(backfill_horas, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reserva",
            name="data",
            field=models.DateField(verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="hora_inicio",
            field=models.TimeField(verbose_name="Hora de inicio"),
        ),
        migrations.AlterField(
            model_name="reserva",
            name="hora_fim",
            field=models.TimeField(verbose_name="Hora de fim"),
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="inicio",
        ),
        migrations.RemoveField(
            model_name="reserva",
            name="duracao_minutos",
        ),
    ]
