# Generated by Django 6.0.1 on 2026-02-04 22:10

import uuid

from django.db import migrations, models


def backfill_series(apps, schema_editor):
    # Sem backfill necessario para serie_id.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("reserva_salas", "0005_reserva_data_horas"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="serie_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_series, migrations.RunPython.noop),
    ]
