# Generated by Django 5.2.10 on 2026-02-06 14:05

import reserva_salas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_salas', '0006_reserva_serie_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data', 'hora_inicio']},
        ),
        migrations.AlterField(
            model_name='sala',
            name='cor',
            field=models.CharField(default=reserva_salas.models.random_sala_color, editable=False, max_length=7, verbose_name='Cor'),
        ),
    ]
