# Generated by Django 6.0.1 on 2026-01-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preposto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepostos', to='empresas.empresa')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
