# Generated by Django 6.0.1 on 2026-01-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaramal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='ramais/'),
        ),
    ]
