# Generated by Django 6.0.1 on 2026-01-23 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0002_pessoaramal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaramal',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='ramais.pessoaramal'),
        ),
    ]
