# Generated by Django 6.0.1 on 2026-01-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0004_pessoaramal_bio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoaramal',
            options={'ordering': ['nome'], 'permissions': [('view_organograma', 'Pode visualizar o organograma')]},
        ),
    ]
