# Generated by Django 6.0.1 on 2026-02-01 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0006_pessoaramal_atualizado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaramal',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ramal_perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoaramal',
            name='nome',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoaramal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
