# Generated by Django 6.0.1 on 2026-02-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ramais", "0007_pessoaramal_usuario_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoaramal",
            name="cargo",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="pessoaramal",
            name="setor",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="pessoaramal",
            name="ramal",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
