# Generated by Django 5.2.10 on 2026-02-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramais', '0008_allow_blank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoaramal',
            name='horario_estudante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='horario_trabalho_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='horario_trabalho_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='intervalo_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='intervalo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='jornada_horas_semanais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='regime_plantao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoaramal',
            name='rg',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
