"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salasituacaopainel',
            options={'verbose_name': 'Sala de Situação', 'verbose_name_plural': 'Sala de Situação'},
        ),
        migrations.AlterField(
            model_name='salasituacaopainel',
            name='titulo',
            field=models.CharField(default='Painel Sala de Situação', max_length=120),
        ),
    ]
