"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0002_alter_salasituacaopainel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorEstrategico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('objetivo_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_estrategicos', to='sala_situacao.objetivoestrategico')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoTatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('objetivo_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_taticos', to='sala_situacao.objetivoestrategico')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorTatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indicador_estrategico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_taticos', to='sala_situacao.indicadorestrategico')),
                ('objetivo_tatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_taticos', to='sala_situacao.objetivotatico')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('indicador_tatico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='sala_situacao.indicadortatico')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='sala_situacao.processo')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='indicadorestrategico',
            constraint=models.UniqueConstraint(fields=('objetivo_estrategico', 'nome'), name='uniq_indicador_estrategico_por_objetivo'),
        ),
        migrations.AddConstraint(
            model_name='objetivotatico',
            constraint=models.UniqueConstraint(fields=('objetivo_estrategico', 'nome'), name='uniq_objetivo_tatico_por_objetivo_estrategico'),
        ),
        migrations.AddConstraint(
            model_name='indicadortatico',
            constraint=models.UniqueConstraint(fields=('objetivo_tatico', 'nome'), name='uniq_indicador_tatico_por_objetivo_tatico'),
        ),
        migrations.AddConstraint(
            model_name='processo',
            constraint=models.UniqueConstraint(fields=('indicador_tatico', 'nome'), name='uniq_processo_por_indicador_tatico'),
        ),
        migrations.AddConstraint(
            model_name='entrega',
            constraint=models.UniqueConstraint(fields=('processo', 'nome'), name='uniq_entrega_por_processo'),
        ),
    ]
