"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0003_objetivoestrategico_indicadorestrategico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='data_entrega_estipulada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='data_entrega_estipulada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='data_entrega_estipulada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='data_entrega_estipulada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivotatico',
            name='data_entrega_estipulada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetivotatico',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_entrega_estipulada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
