"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0006_alter_entrega_data_entrega_estipulada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='evolucao_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use este campo quando o item não possuir filhos relacionados.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Evolução manual (%)'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='evolucao_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use este campo quando o item não possuir filhos relacionados.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Evolução manual (%)'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='evolucao_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use este campo quando o item não possuir filhos relacionados.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Evolução manual (%)'),
        ),
        migrations.AddField(
            model_name='objetivoestrategico',
            name='evolucao_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use este campo quando o item não possuir filhos relacionados.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Evolução manual (%)'),
        ),
        migrations.AddField(
            model_name='objetivotatico',
            name='evolucao_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use este campo quando o item não possuir filhos relacionados.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Evolução manual (%)'),
        ),
        migrations.AddField(
            model_name='processo',
            name='evolucao_manual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use este campo quando o item não possuir filhos relacionados.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Evolução manual (%)'),
        ),
    ]
