"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 16:45

from django.db import migrations, models


def popular_vinculos_objetivo_tatico(apps, schema_editor):
    """Função `popular_vinculos_objetivo_tatico` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    ObjetivoTatico = apps.get_model("sala_situacao", "ObjetivoTatico")
    IndicadorTatico = apps.get_model("sala_situacao", "IndicadorTatico")

    for objetivo_tatico in ObjetivoTatico.objects.all():
        indicador_ids = list(
            IndicadorTatico.objects.filter(objetivo_tatico_id=objetivo_tatico.pk)
            .values_list("indicador_estrategico_id", flat=True)
            .distinct()
        )
        if indicador_ids:
            objetivo_tatico.indicadores_estrategicos.add(*indicador_ids)


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0008_entrega_data_lancamento_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivotatico',
            name='indicadores_estrategicos',
            field=models.ManyToManyField(blank=True, related_name='objetivos_taticos', to='sala_situacao.indicadorestrategico'),
        ),
        migrations.RunPython(popular_vinculos_objetivo_tatico, migrations.RunPython.noop),
    ]
