"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 17:14

from django.db import migrations, models


def migrar_objetivo_estrategico_para_m2m(apps, schema_editor):
    """Função `migrar_objetivo_estrategico_para_m2m` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    IndicadorEstrategico = apps.get_model("sala_situacao", "IndicadorEstrategico")
    for indicador in IndicadorEstrategico.objects.exclude(objetivo_estrategico_id__isnull=True):
        indicador.objetivos_estrategicos.add(indicador.objetivo_estrategico_id)


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0010_remove_indicadortatico_uniq_indicador_tatico_por_objetivo_tatico_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='indicadorestrategico',
            name='uniq_indicador_estrategico_por_objetivo',
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='objetivos_estrategicos',
            field=models.ManyToManyField(related_name='indicadores_estrategicos', to='sala_situacao.objetivoestrategico'),
        ),
        migrations.RunPython(migrar_objetivo_estrategico_para_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='indicadorestrategico',
            name='objetivo_estrategico',
        ),
    ]
