"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-26 18:07

from django.db import migrations, models


def migrar_relacoes_processo_entrega_para_m2m(apps, schema_editor):
    """Função `migrar_relacoes_processo_entrega_para_m2m` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    Processo = apps.get_model("sala_situacao", "Processo")
    Entrega = apps.get_model("sala_situacao", "Entrega")

    for processo in Processo.objects.exclude(indicador_tatico_id__isnull=True):
        processo.indicadores_taticos.add(processo.indicador_tatico_id)

    for entrega in Entrega.objects.exclude(processo_id__isnull=True):
        entrega.processos.add(entrega.processo_id)


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0011_remove_indicadorestrategico_uniq_indicador_estrategico_por_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='processos',
            field=models.ManyToManyField(related_name='entregas', to='sala_situacao.processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='indicadores_taticos',
            field=models.ManyToManyField(related_name='processos', to='sala_situacao.indicadortatico'),
        ),
        migrations.RunPython(migrar_relacoes_processo_entrega_para_m2m, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='entrega',
            name='uniq_entrega_por_processo',
        ),
        migrations.RemoveConstraint(
            model_name='processo',
            name='uniq_processo_por_indicador_tatico',
        ),
        migrations.RemoveField(
            model_name='entrega',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='indicador_tatico',
        ),
    ]
