"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-27 17:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sala_situacao', '0013_notaitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorestrategico',
            name='formula_estrutura',
            field=models.JSONField(blank=True, default=list, verbose_name='Estrutura da fórmula'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='formula_expressao',
            field=models.TextField(blank=True, help_text='Use variáveis por nome e operadores + - * /, por exemplo: (A + B) / C', verbose_name='Fórmula matemática'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='meta_periodo_referencia',
            field=models.CharField(default='Mensal', max_length=80, verbose_name='Período de referência da meta'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='meta_unidade_medida',
            field=models.CharField(default='%', max_length=40, verbose_name='Unidade de medida da meta'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='meta_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da meta'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='periodicidade_monitoramento',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Periodicidade de monitoramento'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='tipo_indicador',
            field=models.CharField(choices=[('PROCESSUAL', 'Processual'), ('MATEMATICO', 'Matemático')], default='PROCESSUAL', max_length=20, verbose_name='Tipo de indicador'),
        ),
        migrations.AddField(
            model_name='indicadorestrategico',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor atual do indicador'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='formula_estrutura',
            field=models.JSONField(blank=True, default=list, verbose_name='Estrutura da fórmula'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='formula_expressao',
            field=models.TextField(blank=True, help_text='Use variáveis por nome e operadores + - * /, por exemplo: (A + B) / C', verbose_name='Fórmula matemática'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='meta_periodo_referencia',
            field=models.CharField(default='Mensal', max_length=80, verbose_name='Período de referência da meta'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='meta_unidade_medida',
            field=models.CharField(default='%', max_length=40, verbose_name='Unidade de medida da meta'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='meta_valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da meta'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='periodicidade_monitoramento',
            field=models.CharField(blank=True, choices=[('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20, verbose_name='Periodicidade de monitoramento'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='tipo_indicador',
            field=models.CharField(choices=[('PROCESSUAL', 'Processual'), ('MATEMATICO', 'Matemático')], default='PROCESSUAL', max_length=20, verbose_name='Tipo de indicador'),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='valor_atual',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor atual do indicador'),
        ),
        migrations.CreateModel(
            name='IndicadorCicloMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('valor_resultado', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_situacao_ciclos', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-periodo_inicio', '-numero'],
                'unique_together': {('content_type', 'object_id', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='IndicadorVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True)),
                ('tipo_numerico', models.CharField(choices=[('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal')], default='DECIMAL', max_length=10)),
                ('unidade_medida', models.CharField(default='%', max_length=40)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_situacao_variaveis', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'unique_together': {('content_type', 'object_id', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='IndicadorCicloHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('registrado_em', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala_situacao_historicos_registrados', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_registros', to='sala_situacao.indicadorciclomonitoramento')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_registros', to='sala_situacao.indicadorvariavel')),
            ],
            options={
                'ordering': ['-registrado_em'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorCicloValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=14)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sala_situacao_valores_atualizados', to=settings.AUTH_USER_MODEL)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='sala_situacao.indicadorciclomonitoramento')),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_ciclo', to='sala_situacao.indicadorvariavel')),
            ],
            options={
                'unique_together': {('ciclo', 'variavel')},
            },
        ),
    ]
