"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-27 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0014_indicadorestrategico_formula_estrutura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='ciclo_monitoramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_monitoramento', to='sala_situacao.indicadorciclomonitoramento'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='valor_monitoramento',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Valor da variável no ciclo'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='variavel_monitoramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_monitoramento', to='sala_situacao.indicadorvariavel'),
        ),
    ]
