"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0015_entrega_ciclo_monitoramento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicadorciclomonitoramento',
            options={'ordering': ['periodo_inicio', 'numero']},
        ),
        migrations.AlterField(
            model_name='indicadorestrategico',
            name='objetivos_estrategicos',
            field=models.ManyToManyField(blank=True, related_name='indicadores_estrategicos', to='sala_situacao.objetivoestrategico'),
        ),
        migrations.AlterField(
            model_name='indicadortatico',
            name='objetivos_taticos',
            field=models.ManyToManyField(blank=True, related_name='indicadores_taticos', to='sala_situacao.objetivotatico'),
        ),
    ]
