"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0016_alter_indicadorciclomonitoramento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicadorestrategico',
            name='meta_periodo_referencia',
        ),
        migrations.RemoveField(
            model_name='indicadortatico',
            name='meta_periodo_referencia',
        ),
    ]
