"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-28 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0017_remove_indicadorestrategico_meta_periodo_referencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoMarcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=60, verbose_name='Marcador')),
                ('cor', models.CharField(blank=True, max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcadores', to='sala_situacao.processo')),
            ],
            options={
                'ordering': ['texto'],
                'unique_together': {('processo', 'texto')},
            },
        ),
    ]
