"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-28 22:23

import random
import django.db.models.deletion
import sala_situacao.models
from django.db import migrations, models


def _normalizar_nome(valor):
    """Função `_normalizar_nome` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `valor`.
    """

    return " ".join((valor or "").strip().split()).casefold()


def migrar_marcadores_legado(apps, schema_editor):
    """Função `migrar_marcadores_legado` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    ProcessoMarcador = apps.get_model("sala_situacao", "ProcessoMarcador")
    Marcador = apps.get_model("sala_situacao", "Marcador")
    MarcadorVinculoItem = apps.get_model("sala_situacao", "MarcadorVinculoItem")
    ContentType = apps.get_model("contenttypes", "ContentType")
    Processo = apps.get_model("sala_situacao", "Processo")

    paleta = [
        "#1f77b4",
        "#ff7f0e",
        "#2ca02c",
        "#d62728",
        "#9467bd",
        "#8c564b",
        "#e377c2",
        "#17becf",
        "#bcbd22",
        "#7f7f7f",
    ]

    processo_ct, _ = ContentType.objects.get_or_create(
        app_label=Processo._meta.app_label,
        model=Processo._meta.model_name,
    )

    marcador_por_nome = {}
    for legado in ProcessoMarcador.objects.all().order_by("id"):
        nome = " ".join((legado.texto or "").strip().split())
        if not nome:
            continue
        nome_normalizado = _normalizar_nome(nome)
        marcador = marcador_por_nome.get(nome_normalizado)
        if marcador is None:
            cor = (legado.cor or "").strip()
            if not cor.startswith("#") or len(cor) != 7:
                cor = random.choice(paleta)
            marcador, _ = Marcador.objects.get_or_create(
                nome_normalizado=nome_normalizado,
                defaults={"nome": nome, "cor": cor, "ativo": True},
            )
            marcador_por_nome[nome_normalizado] = marcador

        MarcadorVinculoItem.objects.get_or_create(
            content_type=processo_ct,
            object_id=legado.processo_id,
            marcador_id=marcador.id,
        )


def reverse_marcadores_legado(apps, schema_editor):
    # Migração reversa intencionalmente sem reconstrução do legado textual por processo.
    """Função `reverse_marcadores_legado` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    pass


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sala_situacao', '0018_processomarcador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('nome_normalizado', models.CharField(max_length=60, unique=True)),
                ('cor', models.CharField(default=sala_situacao.models.escolher_cor_marcador, max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MarcadorVinculoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_situacao_marcadores_itens', to='contenttypes.contenttype')),
                ('marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_itens', to='sala_situacao.marcador')),
            ],
            options={
                'ordering': ['marcador__nome'],
                'unique_together': {('content_type', 'object_id', 'marcador')},
            },
        ),
        migrations.RunPython(migrar_marcadores_legado, reverse_marcadores_legado),
    ]
