"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-02-28 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('sala_situacao', '0019_marcador_marcadorvinculoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorvariavel',
            name='origem_reaproveitada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicadorvariavel',
            name='variavel_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variaveis_reutilizadas', to='sala_situacao.indicadorvariavel'),
        ),
        migrations.AddConstraint(
            model_name='indicadorvariavel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origem_reaproveitada', False), ('variavel_origem__isnull', True)), models.Q(('origem_reaproveitada', True), ('variavel_origem__isnull', False)), _connector='OR'), name='ck_indicadorvariavel_reuso_consistente'),
        ),
    ]
