"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-03-02 19:33

from django.db import migrations, models


def migrar_vinculos_ie_it(apps, schema_editor):
    """Função `migrar_vinculos_ie_it` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    IndicadorTatico = apps.get_model("sala_situacao", "IndicadorTatico")
    ObjetivoTatico = apps.get_model("sala_situacao", "ObjetivoTatico")

    through_it_ot = IndicadorTatico.objetivos_taticos.through
    through_ot_ie = ObjetivoTatico.indicadores_estrategicos.through
    through_it_ie = IndicadorTatico.indicadores_estrategicos.through

    objetivo_para_ies = {}
    for row in through_ot_ie.objects.all().values("objetivotatico_id", "indicadorestrategico_id"):
        objetivo_para_ies.setdefault(row["objetivotatico_id"], set()).add(row["indicadorestrategico_id"])

    pares_it_ie = set()
    for row in through_it_ot.objects.all().values("indicadortatico_id", "objetivotatico_id"):
        for ie_id in objetivo_para_ies.get(row["objetivotatico_id"], set()):
            pares_it_ie.add((row["indicadortatico_id"], ie_id))

    for it_id, ie_id in pares_it_ie:
        through_it_ie.objects.get_or_create(
            indicadortatico_id=it_id,
            indicadorestrategico_id=ie_id,
        )


def noop(apps, schema_editor):
    """Função `noop` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    return


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0020_indicadorvariavel_origem_reaproveitada_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS sala_situacao_indicadortatico_indicadores_estrategicos;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='indicadores_estrategicos',
            field=models.ManyToManyField(blank=True, related_name='indicadores_taticos', to='sala_situacao.indicadorestrategico'),
        ),
        migrations.RunPython(migrar_vinculos_ie_it, noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS sala_situacao_indicadorestrategico_objetivos_estrategicos;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS sala_situacao_indicadortatico_objetivos_taticos;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS sala_situacao_objetivotatico_indicadores_estrategicos;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS sala_situacao_objetivotatico;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS sala_situacao_objetivoestrategico;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='indicadorestrategico',
                    name='objetivos_estrategicos',
                ),
                migrations.RemoveField(
                    model_name='objetivotatico',
                    name='objetivo_estrategico',
                ),
                migrations.RemoveField(
                    model_name='objetivotatico',
                    name='indicadores_estrategicos',
                ),
                migrations.RemoveField(
                    model_name='indicadortatico',
                    name='objetivos_taticos',
                ),
                migrations.DeleteModel(
                    name='ObjetivoEstrategico',
                ),
                migrations.DeleteModel(
                    name='ObjetivoTatico',
                ),
            ],
        ),
    ]
