"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-03-03

from django.db import migrations, models
import django.db.models.deletion


def _migrar_ciclos_para_variavel(apps, schema_editor):
    """Função `_migrar_ciclos_para_variavel` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    CicloAntigo = apps.get_model("sala_situacao", "IndicadorCicloMonitoramento")
    CicloNovo = apps.get_model("sala_situacao", "IndicadorVariavelCicloMonitoramento")
    Entrega = apps.get_model("sala_situacao", "Entrega")
    Valor = apps.get_model("sala_situacao", "IndicadorCicloValor")
    Historico = apps.get_model("sala_situacao", "IndicadorCicloHistorico")

    cache = {}

    def get_or_create_ciclo_novo(variavel_id, ciclo_antigo_id):
        """Função `_migrar_ciclos_para_variavel.get_or_create_ciclo_novo` com finalidade específica no fluxo do app.

        Explicação pedagógica:
        - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
        - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
        - Parâmetros recebidos: `variavel_id`, `ciclo_antigo_id`.
        """

        if not variavel_id or not ciclo_antigo_id:
            return None
        key = (variavel_id, ciclo_antigo_id)
        if key in cache:
            return cache[key]
        ciclo_antigo = CicloAntigo.objects.filter(pk=ciclo_antigo_id).first()
        if not ciclo_antigo:
            return None
        ciclo_novo, _ = CicloNovo.objects.get_or_create(
            variavel_id=variavel_id,
            numero=ciclo_antigo.numero,
            defaults={
                "periodo_inicio": ciclo_antigo.periodo_inicio,
                "periodo_fim": ciclo_antigo.periodo_fim,
                "status": ciclo_antigo.status,
            },
        )
        cache[key] = ciclo_novo.id
        return ciclo_novo.id

    for valor in Valor.objects.all().iterator():
        novo_id = get_or_create_ciclo_novo(valor.variavel_id, valor.ciclo_id)
        if novo_id:
            valor.ciclo_variavel_id = novo_id
            valor.save(update_fields=["ciclo_variavel"])

    for hist in Historico.objects.all().iterator():
        novo_id = get_or_create_ciclo_novo(hist.variavel_id, hist.ciclo_id)
        if novo_id:
            hist.ciclo_variavel_id = novo_id
            hist.save(update_fields=["ciclo_variavel"])

    for entrega in Entrega.objects.all().iterator():
        novo_id = get_or_create_ciclo_novo(entrega.variavel_monitoramento_id, entrega.ciclo_monitoramento_id)
        if novo_id:
            entrega.ciclo_monitoramento_variavel_id = novo_id
            entrega.save(update_fields=["ciclo_monitoramento_variavel"])


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ("sala_situacao", "0022_indicador_tipo_acumulativo_e_periodicidade_variavel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicadorestrategico",
            name="periodicidade_monitoramento",
        ),
        migrations.RemoveField(
            model_name="indicadortatico",
            name="periodicidade_monitoramento",
        ),
        migrations.AlterField(
            model_name="indicadorvariavel",
            name="periodicidade_monitoramento",
            field=models.CharField(
                choices=[
                    ("SEMANAL", "Semanal"),
                    ("QUINZENAL", "Quinzenal"),
                    ("MENSAL", "Mensal"),
                    ("TRIMESTRAL", "Trimestral"),
                    ("SEMESTRAL", "Semestral"),
                    ("ANUAL", "Anual"),
                ],
                help_text="Periodicidade obrigatória para geração do monitoramento da variável.",
                max_length=20,
                verbose_name="Periodicidade de monitoramento da variável",
            ),
        ),
        migrations.CreateModel(
            name="IndicadorVariavelCicloMonitoramento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero", models.PositiveIntegerField()),
                ("periodo_inicio", models.DateField()),
                ("periodo_fim", models.DateField()),
                ("status", models.CharField(choices=[("ABERTO", "Aberto"), ("FECHADO", "Fechado")], default="ABERTO", max_length=10)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "variavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ciclos_monitoramento",
                        to="sala_situacao.indicadorvariavel",
                    ),
                ),
            ],
            options={
                "ordering": ["periodo_inicio", "numero"],
            },
        ),
        migrations.AddField(
            model_name="entrega",
            name="ciclo_monitoramento_variavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entregas_monitoramento",
                to="sala_situacao.indicadorvariavelciclomonitoramento",
            ),
        ),
        migrations.AddField(
            model_name="indicadorciclohistorico",
            name="ciclo_variavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historico_registros",
                to="sala_situacao.indicadorvariavelciclomonitoramento",
            ),
        ),
        migrations.AddField(
            model_name="indicadorciclovalor",
            name="ciclo_variavel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valores",
                to="sala_situacao.indicadorvariavelciclomonitoramento",
            ),
        ),
        migrations.RunPython(_migrar_ciclos_para_variavel, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="indicadorciclovalor",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="entrega",
            name="ciclo_monitoramento",
        ),
        migrations.RemoveField(
            model_name="indicadorciclohistorico",
            name="ciclo",
        ),
        migrations.RemoveField(
            model_name="indicadorciclovalor",
            name="ciclo",
        ),
        migrations.RenameField(
            model_name="entrega",
            old_name="ciclo_monitoramento_variavel",
            new_name="ciclo_monitoramento",
        ),
        migrations.RenameField(
            model_name="indicadorciclohistorico",
            old_name="ciclo_variavel",
            new_name="ciclo",
        ),
        migrations.RenameField(
            model_name="indicadorciclovalor",
            old_name="ciclo_variavel",
            new_name="ciclo",
        ),
        migrations.AlterUniqueTogether(
            name="indicadorciclovalor",
            unique_together={("ciclo", "variavel")},
        ),
        migrations.AddIndex(
            model_name="indicadorvariavelciclomonitoramento",
            index=models.Index(fields=["variavel", "periodo_fim"], name="sala_situac_variave_fa6a8b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="indicadorvariavelciclomonitoramento",
            unique_together={("variavel", "numero")},
        ),
    ]
