"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-03-03 18:25

from datetime import timedelta

from django.db import migrations, models


def _primeiro_dia_mes(data_base):
    """Função `_primeiro_dia_mes` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `data_base`.
    """

    return data_base.replace(day=1)


def _ultimo_dia_mes(data_base):
    """Função `_ultimo_dia_mes` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `data_base`.
    """

    proximo_mes = data_base.replace(day=28) + timedelta(days=4)
    return proximo_mes - timedelta(days=proximo_mes.day)


def _backfill_periodos_entrega_e_ciclo_inicial(apps, schema_editor):
    """Função `_backfill_periodos_entrega_e_ciclo_inicial` com finalidade específica no fluxo do app.

    Explicação pedagógica:
    - Executa uma etapa de negócio/infraestrutura dentro de `sala_situacao`.
    - O retorno e os efeitos colaterais devem ser lidos junto com chamadas no código.
    - Parâmetros recebidos: `apps`, `schema_editor`.
    """

    Entrega = apps.get_model("sala_situacao", "Entrega")
    IndicadorVariavel = apps.get_model("sala_situacao", "IndicadorVariavel")
    Ciclo = apps.get_model("sala_situacao", "IndicadorVariavelCicloMonitoramento")

    for entrega in Entrega.objects.select_related("ciclo_monitoramento").all().iterator():
        referencia = None
        if entrega.ciclo_monitoramento_id and entrega.ciclo_monitoramento and entrega.ciclo_monitoramento.periodo_inicio:
            referencia = entrega.ciclo_monitoramento.periodo_inicio
        elif entrega.data_entrega_estipulada:
            referencia = entrega.data_entrega_estipulada
        elif entrega.data_lancamento:
            referencia = entrega.data_lancamento
        if not referencia:
            continue
        entrega.periodo_inicio = _primeiro_dia_mes(referencia)
        entrega.periodo_fim = _ultimo_dia_mes(referencia)
        entrega.save(update_fields=["periodo_inicio", "periodo_fim"])

    periodicidades_longas = {"TRIMESTRAL", "SEMESTRAL", "ANUAL"}
    for variavel in IndicadorVariavel.objects.filter(periodicidade_monitoramento__in=periodicidades_longas).iterator():
        ciclo_inicial = (
            Ciclo.objects.filter(variavel_id=variavel.id)
            .order_by("numero", "periodo_inicio", "id")
            .first()
        )
        if not ciclo_inicial:
            continue
        if not ciclo_inicial.eh_inicial:
            ciclo_inicial.eh_inicial = True
            ciclo_inicial.save(update_fields=["eh_inicial"])


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('sala_situacao', '0023_monitoramento_por_variavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='periodo_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicadorvariavelciclomonitoramento',
            name='eh_inicial',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indicadorvariavelciclomonitoramento',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('LEGADO', 'Legado')], default='ABERTO', max_length=10),
        ),
        migrations.RunPython(_backfill_periodos_entrega_e_ciclo_inicial, migrations.RunPython.noop),
    ]
