"""
Migração de banco: registra mudanças estruturais/evolutivas no schema e dados.

Leitura recomendada para iniciantes: comece pelos itens públicos deste arquivo,
siga para dependências chamadas e confira os testes para observar cenários reais.
"""

# Generated by Django 5.2.10 on 2026-03-04 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    """Representa a estrutura `Migration` no app `sala_situacao`.

    Esta classe concentra regras e comportamentos relacionados ao domínio
    de monitoramento/gestão do painel. Para auditoria, leia os métodos na
    ordem para entender como os dados entram, são validados e persistidos.
    """

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sala_situacao', '0026_entrega_monitoramento_evidencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorestrategico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_indicadores_criados_sala', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadortatico',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_indicadores_criados_sala', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='indicadorvariavel',
            name='grupos_monitoramento',
            field=models.ManyToManyField(blank=True, related_name='variaveis_monitoramento_sala', to='auth.group'),
        ),
        migrations.AddField(
            model_name='processo',
            name='origem_automatica_monitoramento',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MarcadorVinculoAutomaticoGrupoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_situacao_marcadores_automaticos_grupo_itens', to='contenttypes.contenttype')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_automaticos_marcadores_sala', to='auth.group')),
                ('marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_automaticos_grupo_itens', to='sala_situacao.marcador')),
            ],
            options={
                'ordering': ['marcador__nome'],
                'unique_together': {('content_type', 'object_id', 'grupo')},
            },
        ),
    ]
