# Generated by Django 5.2.10 on 2026-03-19 17:10

from django.db import migrations, models


def migrar_vinculos_taticos_para_estrategicos(apps, schema_editor):
    Processo = apps.get_model("sala_situacao", "Processo")
    through_tatico = Processo.indicadores_taticos.through
    through_estrategico = Processo.indicadores_estrategicos.through
    IndicadorTatico = apps.get_model("sala_situacao", "IndicadorTatico")

    taticos_para_estrategicos = {}
    for tatico in IndicadorTatico.objects.all():
        taticos_para_estrategicos[tatico.id] = set(
            tatico.indicadores_estrategicos.values_list("id", flat=True)
        )

    novos_vinculos = set()
    for row in through_tatico.objects.all().values("processo_id", "indicadortatico_id"):
        for estrategico_id in taticos_para_estrategicos.get(row["indicadortatico_id"], set()):
            novos_vinculos.add((row["processo_id"], estrategico_id))

    for processo_id, estrategico_id in novos_vinculos:
        through_estrategico.objects.get_or_create(
            processo_id=processo_id,
            indicadorestrategico_id=estrategico_id,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('sala_situacao', '0028_backfill_origem_automatica_monitoramento'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='indicadores_estrategicos',
            field=models.ManyToManyField(related_name='processos', to='sala_situacao.indicadorestrategico'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='indicadores_taticos',
            field=models.ManyToManyField(blank=True, related_name='processos', to='sala_situacao.indicadortatico'),
        ),
        migrations.RunPython(migrar_vinculos_taticos_para_estrategicos, migrations.RunPython.noop),
    ]
