# Generated by Django 5.2.10 on 2026-03-20 01:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_lancamento', models.DateField(blank=True, editable=False, null=True, verbose_name='Data de lancamento')),
                ('data_lancamento_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de lancamento (timestamp)')),
                ('data_entrega_estipulada', models.DateField(blank=True, null=True, verbose_name='Data de entrega estipulada')),
                ('evolucao_manual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_indicador', models.CharField(choices=[('PROCESSUAL', 'Processual'), ('MATEMATICO', 'Matematico'), ('MATEMATICO_ACUMULATIVO', 'Matematico Acumulativo')], default='PROCESSUAL', max_length=32)),
                ('formula_expressao', models.TextField(blank=True, default='')),
                ('meta_valor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('meta_unidade_medida', models.CharField(blank=True, default='%', max_length=40)),
                ('valor_atual', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('grupos_responsaveis', models.ManyToManyField(blank=True, related_name='%(class)s_v2_responsavel', to='auth.group')),
            ],
            options={
                'verbose_name': 'Indicador V2',
                'verbose_name_plural': 'Indicadores V2',
                'ordering': ['nome', 'id'],
                'permissions': (('monitorar_indicador', 'Pode monitorar indicador v2'),),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_lancamento', models.DateField(blank=True, editable=False, null=True, verbose_name='Data de lancamento')),
                ('data_lancamento_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de lancamento (timestamp)')),
                ('data_entrega_estipulada', models.DateField(blank=True, null=True, verbose_name='Data de entrega estipulada')),
                ('evolucao_manual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupos_responsaveis', models.ManyToManyField(blank=True, related_name='%(class)s_v2_responsavel', to='auth.group')),
                ('indicadores', models.ManyToManyField(blank=True, related_name='processos', to='sala_situacao_v2.indicador')),
            ],
            options={
                'verbose_name': 'Processo V2',
                'verbose_name_plural': 'Processos V2',
                'ordering': ['nome', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, default='')),
                ('data_lancamento', models.DateField(blank=True, editable=False, null=True, verbose_name='Data de lancamento')),
                ('data_lancamento_em', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data de lancamento (timestamp)')),
                ('data_entrega_estipulada', models.DateField(blank=True, null=True, verbose_name='Data de entrega estipulada')),
                ('evolucao_manual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('valor_monitoramento', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('evidencia_monitoramento', models.FileField(blank=True, null=True, upload_to='sala_situacao_v2/evidencias/')),
                ('monitorado_em', models.DateTimeField(blank=True, null=True)),
                ('grupos_responsaveis', models.ManyToManyField(blank=True, related_name='%(class)s_v2_responsavel', to='auth.group')),
                ('processos', models.ManyToManyField(blank=True, related_name='entregas', to='sala_situacao_v2.processo')),
            ],
            options={
                'verbose_name': 'Entrega V2',
                'verbose_name_plural': 'Entregas V2',
                'ordering': ['nome', 'id'],
                'permissions': (('monitorar_entrega', 'Pode monitorar entrega v2'),),
                'abstract': False,
            },
        ),
    ]
