# Generated by Django 5.2.10 on 2026-03-20 01:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala_situacao_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador',
            name='meta_valor',
            field=models.DecimalField(decimal_places=4, default=Decimal('100'), max_digits=18),
        ),
    ]
