# Generated by Django 5.2.10 on 2026-03-20 01:53

import django.db.models.deletion
import sala_situacao_v2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('sala_situacao_v2', '0002_alter_indicador_meta_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('nome_normalizado', models.CharField(max_length=60, unique=True)),
                ('cor', models.CharField(default=sala_situacao_v2.models.escolher_cor_marcador, max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MarcadorVinculoAutomaticoGrupoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sala_situacao_v2_marcadores_automaticos_grupo_itens', to='contenttypes.contenttype')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_automaticos_marcadores_sala_v2', to='auth.group')),
                ('marcador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_automaticos_grupo_itens_v2', to='sala_situacao_v2.marcador')),
            ],
            options={
                'ordering': ['marcador__nome'],
                'unique_together': {('content_type', 'object_id', 'grupo')},
            },
        ),
    ]
