# Generated by Django 5.2.10 on 2026-03-20 02:03

from django.db import migrations, models


def backfill_grupos_criadores(apps, schema_editor):
    Processo = apps.get_model("sala_situacao_v2", "Processo")
    for processo in Processo.objects.all().iterator():
        grupos_ids = list(processo.grupos_responsaveis.values_list("id", flat=True))
        if grupos_ids:
            processo.grupos_criadores.add(*grupos_ids)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sala_situacao_v2', '0003_marcador_marcadorvinculoautomaticogrupoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='grupos_criadores',
            field=models.ManyToManyField(blank=True, related_name='processos_v2_criados', to='auth.group'),
        ),
        migrations.RunPython(backfill_grupos_criadores, noop_reverse),
    ]
