# Generated by Django 5.2.10 on 2026-03-20 02:09

from django.db import migrations, models


def backfill_grupos_criadores(apps, schema_editor):
    Indicador = apps.get_model("sala_situacao_v2", "Indicador")
    for indicador in Indicador.objects.all().iterator():
        grupos_ids = list(indicador.grupos_responsaveis.values_list("id", flat=True))
        if grupos_ids:
            indicador.grupos_criadores.add(*grupos_ids)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sala_situacao_v2', '0004_processo_grupos_criadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='grupos_criadores',
            field=models.ManyToManyField(blank=True, related_name='indicadores_v2_criados', to='auth.group'),
        ),
        migrations.RunPython(backfill_grupos_criadores, noop_reverse),
    ]
