# Generated by Django 5.2.10 on 2026-03-20 02:11

from django.db import migrations, models


def backfill_grupos_criadores(apps, schema_editor):
    Entrega = apps.get_model("sala_situacao_v2", "Entrega")
    for entrega in Entrega.objects.all().iterator():
        grupos_ids = list(entrega.grupos_responsaveis.values_list("id", flat=True))
        if grupos_ids:
            entrega.grupos_criadores.add(*grupos_ids)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sala_situacao_v2', '0005_indicador_grupos_criadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='grupos_criadores',
            field=models.ManyToManyField(blank=True, related_name='entregas_v2_criadas', to='auth.group'),
        ),
        migrations.RunPython(backfill_grupos_criadores, noop_reverse),
    ]
