# Generated by Django 5.2.10 on 2026-03-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sala_situacao_v2', '0006_entrega_grupos_criadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='periodo_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrega',
            name='periodo_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IndicadorVariavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, default='')),
                ('tipo_numerico', models.CharField(choices=[('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal')], default='DECIMAL', max_length=10)),
                ('unidade_medida', models.CharField(default='%', max_length=40)),
                ('periodicidade_monitoramento', models.CharField(choices=[('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], max_length=20)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupos_monitoramento', models.ManyToManyField(blank=True, related_name='variaveis_monitoramento_sala_v2', to='auth.group')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variaveis', to='sala_situacao_v2.indicador')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
                'unique_together': {('indicador', 'nome')},
            },
        ),
        migrations.AddField(
            model_name='entrega',
            name='variavel_monitoramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_monitoramento', to='sala_situacao_v2.indicadorvariavel'),
        ),
        migrations.CreateModel(
            name='IndicadorVariavelCicloMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('eh_inicial', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos_monitoramento', to='sala_situacao_v2.indicadorvariavel')),
            ],
            options={
                'ordering': ['periodo_inicio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='IndicadorCicloValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=18)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('variavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_ciclo', to='sala_situacao_v2.indicadorvariavel')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='sala_situacao_v2.indicadorvariavelciclomonitoramento')),
            ],
        ),
        migrations.AddField(
            model_name='entrega',
            name='ciclo_monitoramento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_monitoramento', to='sala_situacao_v2.indicadorvariavelciclomonitoramento'),
        ),
        migrations.AddIndex(
            model_name='indicadorvariavelciclomonitoramento',
            index=models.Index(fields=['variavel', 'periodo_fim'], name='sala_situac_variave_2dcbca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='indicadorvariavelciclomonitoramento',
            unique_together={('variavel', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='indicadorciclovalor',
            unique_together={('ciclo', 'variavel')},
        ),
    ]
