# Generated by Django 5.2.10 on 2026-03-20 11:13

import django.core.validators
from django.db import migrations, models


def _backfill_dia_referencia_e_ressincronizar(apps, schema_editor):
    from sala_situacao_v2.models import Indicador, IndicadorVariavel

    for variavel in IndicadorVariavel.objects.select_related("indicador").all():
        indicador = variavel.indicador
        dia_referencia = 1
        if indicador and indicador.data_lancamento:
            dia_referencia = indicador.data_lancamento.day
        variavel.dia_referencia_monitoramento = dia_referencia
        variavel.save(update_fields=["dia_referencia_monitoramento", "atualizado_em"])

    for indicador in Indicador.objects.all():
        if indicador.eh_indicador_matematico:
            indicador.sincronizar_estrutura_processual_monitoramento()


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('sala_situacao_v2', '0007_entrega_periodo_fim_entrega_periodo_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorvariavel',
            name='dia_referencia_monitoramento',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.RunPython(_backfill_dia_referencia_e_ressincronizar, _noop_reverse),
    ]
