"""
Migração de banco: descreve mudanças evolutivas de schema e/ou dados.

Guia pedagógico: leia de cima para baixo e acompanhe chamadas entre funções,
comparando com os testes e com os pontos de entrada HTTP/ORM para auditoria.
"""

# Generated by Django 5.2.10 on 2026-02-24 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Classe `Migration` do app `licitacoes`.

    Objetivo pedagógico:
    - Organiza comportamento e estado relacionados a uma parte do domínio.
    - Em auditoria, inspecione métodos públicos e pontos de escrita em banco.
    """

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TermoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=180)),
                ('processo_sei', models.CharField(max_length=120, verbose_name='Processo SEI')),
                ('link_processo_sei', models.URLField(blank=True, max_length=500, verbose_name='Link do Processo SEI')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['apelido', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitens', to='licitacoes.itemsessao')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='licitacoes.sessaotermo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sessaotermo',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='licitacoes.termoreferencia'),
        ),
    ]
