"""
Migração de banco: descreve mudanças evolutivas de schema e/ou dados.

Guia pedagógico: leia de cima para baixo e acompanhe chamadas entre funções,
comparando com os testes e com os pontos de entrada HTTP/ORM para auditoria.
"""

# Generated by Django 5.2.10 on 2026-02-24 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Classe `Migration` do app `licitacoes`.

    Objetivo pedagógico:
    - Organiza comportamento e estado relacionados a uma parte do domínio.
    - Em auditoria, inspecione métodos públicos e pontos de escrita em banco.
    """

    dependencies = [
        ('licitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaItemLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('catmat_catser', models.CharField(blank=True, max_length=120, verbose_name='CATMAT/CATSER')),
                ('siafisico', models.CharField(blank=True, max_length=120, verbose_name='Siafisico')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabela_linhas', to='licitacoes.itemsessao')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
