"""
Migração de banco: descreve mudanças evolutivas de schema e/ou dados.

Guia pedagógico: leia de cima para baixo e acompanhe chamadas entre funções,
comparando com os testes e com os pontos de entrada HTTP/ORM para auditoria.
"""

# Generated by Django 5.2.10 on 2026-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    """Classe `Migration` do app `licitacoes`.

    Objetivo pedagógico:
    - Organiza comportamento e estado relacionados a uma parte do domínio.
    - Em auditoria, inspecione métodos públicos e pontos de escrita em banco.
    """

    dependencies = [
        ('licitacoes', '0002_tabelaitemlinha'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelaitemlinha',
            name='unidade_fornecimento',
            field=models.CharField(blank=True, max_length=120, verbose_name='Unidade de Fornecimento'),
        ),
    ]
