"""
Migração de banco: descreve mudanças evolutivas de schema e/ou dados.

Guia pedagógico: leia de cima para baixo e acompanhe chamadas entre funções,
comparando com os testes e com os pontos de entrada HTTP/ORM para auditoria.
"""

# Generated by Django 5.2.10 on 2026-02-24 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    """Classe `Migration` do app `licitacoes`.

    Objetivo pedagógico:
    - Organiza comportamento e estado relacionados a uma parte do domínio.
    - Em auditoria, inspecione métodos públicos e pontos de escrita em banco.
    """

    dependencies = [
        ('licitacoes', '0003_tabelaitemlinha_unidade_fornecimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsessaoTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsessoes', to='licitacoes.sessaotermo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='itemsessao',
            name='subsessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='licitacoes.subsessaotermo'),
        ),
    ]
