# Generated by Django 5.2.10 on 2026-04-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notificacaousuario',
            new_name='notificacoe_user_id_093e5b_idx',
            old_name='notificacoe_user_id_dc6315_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaousuario',
            new_name='notificacoe_user_id_fafcbb_idx',
            old_name='notificacoe_user_cr_1daa90_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaousuario',
            new_name='notificacoe_user_id_8f082f_idx',
            old_name='notificacoe_user_re_baa0bc_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaousuario',
            new_name='notificacoe_user_id_aefca2_idx',
            old_name='notificacoe_user_di_4ebe14_idx',
        ),
        migrations.RenameIndex(
            model_name='notificacaousuario',
            new_name='notificacoe_user_id_cfc1ee_idx',
            old_name='notificacoe_user_de_1ef85f_idx',
        ),
    ]
