"""
Migração inicial do app `empresas`.

Cria a tabela base de empresas com nome único e CNPJ opcional.
"""

# Generated by Django 6.0.1 on 2026-01-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    """Representa uma etapa versionada de evolução de schema do app."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
