# Generated by Django 6.0.1 on 2026-01-28 13:09
"""
Migração inicial do app `contratos`.

Cria a estrutura base da entidade `Contrato` no banco de dados.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Define o estado inicial de schema para o módulo de contratos."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_sei', models.CharField(max_length=120)),
                ('nro_contrato', models.CharField(max_length=120)),
                ('objeto', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('data_inicial', models.DateField()),
                ('vigencia_meses', models.IntegerField(choices=[(12, '12 meses'), (24, '24 meses'), (36, '36 meses'), (48, '48 meses')])),
                ('data_fim', models.DateField(editable=False)),
                ('prorrogacao_maxima_meses', models.IntegerField(choices=[(60, '60 meses'), (120, '120 meses')])),
            ],
            options={
                'ordering': ['-data_fim', 'nro_sei'],
            },
        ),
    ]
