# Generated by Django 6.0.1 on 2026-01-28 13:49
"""
Migração evolutiva do app `contratos`.

Adiciona vínculo opcional de contrato com empresa (`empresas.empresa`).
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Aplica relacionamento com entidade de empresa na tabela de contratos."""

    dependencies = [
        ('contratos', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='empresas.empresa'),
        ),
    ]
