# Generated by Django 6.0.1 on 2026-01-28 21:49
"""
Migração evolutiva do app `contratos`.

Ajusta `data_fim` para permitir preenchimento flexível em etapas de cadastro.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Altera restrições do campo `data_fim` no modelo `Contrato`."""

    dependencies = [
        ('contratos', '0002_contrato_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True),
        ),
    ]
