# Generated by Django 6.0.1 on 2026-01-29 13:25
"""
Migração evolutiva do app `contratos`.

Introduz campo de status contratual e flexibiliza null/blank em campos
de vigência e valores para refletir ciclo real de preenchimento.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Consolida ajustes de domínio no schema de `Contrato`."""

    dependencies = [
        ('contratos', '0003_alter_contrato_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(blank=True, choices=[('ENCERRADO', 'Encerrado'), ('VIGENTE', 'Vigente'), ('EM_CONTRATACAO', 'Em Contratacao')], default='VIGENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nro_contrato',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='prorrogacao_maxima_meses',
            field=models.IntegerField(blank=True, choices=[(60, '60 meses'), (120, '120 meses')], null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='vigencia_meses',
            field=models.IntegerField(blank=True, choices=[(12, '12 meses'), (24, '24 meses'), (36, '36 meses'), (48, '48 meses')], null=True),
        ),
    ]
