# Generated by Django 6.0.1 on 2026-01-29 18:47
"""
Migração evolutiva do app `contratos`.

Adiciona metadados de rastreabilidade de atualização (`atualizado_em` e
`atualizado_por`) para auditoria operacional.
"""

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Evolui schema para suportar trilha de atualização de contratos."""

    dependencies = [
        ('contratos', '0004_contrato_status_alter_contrato_data_fim_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='atualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_atualizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
