# Generated by Django 5.2.10 on 2026-01-31 03:24
"""
Migração evolutiva do app `contratos`.

Inclui campo de link externo para processo administrativo associado ao contrato.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Adiciona suporte a URL do processo no modelo `Contrato`."""

    dependencies = [
        ('contratos', '0005_contrato_atualizado_em_contrato_atualizado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='link_processo',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link do processo'),
        ),
    ]
