# Generated by Django 5.2.10 on 2026-04-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreamento_navegacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dailypagevisit',
            new_name='rastreament_visited_58b60f_idx',
            old_name='rastreamen_visited_0eb8d0_idx',
        ),
        migrations.RenameIndex(
            model_name='dailypagevisit',
            new_name='rastreament_path_90d497_idx',
            old_name='rastreamen_path_4b4d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='dailypagevisit',
            new_name='rastreament_visited_5f1efc_idx',
            old_name='rastreamen_visited_46303d_idx',
        ),
        migrations.AlterField(
            model_name='dailypagevisit',
            name='path',
            field=models.CharField(max_length=512, verbose_name='Caminho'),
        ),
    ]
